export const colors: Record<string, string> = {
  TEXT_MAIN: '#EADDFF',
  BACKGROUND: '#6868EA',
  PRIMARY_COLOR: '#8B4513',
  SECONDARY_COLOR: '#000000',
  COMMON_GAME_AREA_BACKGROUND_COLOR: '#592d06',
  CARDS_SECONDARY_BACKGROUND_COLOR: '#A0522D',
  GAME_AREA_CIRCLE_BLOCK_HOVER_COLOR: '#FFFF00',
  GAME_AREA_CIRCLE_BLOCK_BACKGROUND_COLOR: '#8D5120',
  CARDS_LIST_BACKGROUND_COLOR: '#481601',
  GAME_AREA_BACKGROUND_COLOR: '#503017',
};
